---
kind: pipeline
type: docker
name: backend

steps:
- name: run tests
  image: python:3.8
  commands:
  - pip install poetry
  - poetry install
  - cd tests
  - poetry run pytest

trigger:
  event:
    exclude:
    - pull_request
